sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "iojs"
  - "6"
cache:
  directories:
  - "node_modules"
  - "$HOME/.npm"
env:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary
  global:
  - JOBS=1
before_install:
  # setting the path for phantom.js 2.0.0
    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
- npm i -g npm@^5.6.0
- npm config set spin false
install:
    - mkdir travis-phantomjs
    - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
    - export PATH=$PWD/travis-phantomjs:$PATH
    - npm install -g bower
    - npm install
    - bower install
script:
- ember test --server
- npm run lint:js
- npm test
deploy:
  provider: heroku
  api_key:
    secure: SuBm5FCx9r+JxISSy4uZ1MVTrExXyST2pJefmGo2E644Xj+veUuBvYuef1rFrGA9SUvOIPTJpkjLE0gq2Rp/gYsJWmH0UamlzatuU0/LsUldmwSTRB19sR4cb7YipB7D/7LPUc0CHHm+i4p4cEdfeM/lGuZoaLqJyOZ4/WinTMtj+wJAOHZbAYEWvofnW9DleDc5URcWc/hKCa9CczQGO+4cHDiCqQEGwzIsR7mfZhLbTuP+jjoZpOvRX2u+OdsotXiaOZ7zfCKeg9m4bei45mg+3RCHlqWlcJVcxY25lbkIw5IzdqJ+Cq7fggHKPUTizDl2k1mZeLzK+hK471C7dxRLwg7g8hQgPEbZDhHCy0anHYexBflkhAZcwr9f9FFNYvWqZ1ZhEls8zTO9VGjXcd71kzGLfwA9wiIxPo0YZ94JmVTSZrJcjooZGhqxLt5e7dveF8zfNeJCys4jMnWqBcrjm1F1IMhHPzM2F0D2DhLq72EJV3LwCl93kZ+GVgxFYrEoPD1FgmXESJ7Zf0bPNSJzqz/ZSMco/a9oS/W6qbkkz5PnQvBD6IO4geiniocCRsG7QOKD/QU9mtpvDyuas9vuTsfFllYzrE/Zc4k/jadz2LgV/VNBj4WpsXmnTCQ+UPubmLuxX/7SPdVucygu3jIZk9ZR16fpXmpbIDs+hgc=
  app: boiling-atoll-18834
  on:
    repo: iamranveer/ui
